// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://putwiqqfwftndkrwalkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1dHdpcXFmd2Z0bmRrcndhbGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1Mzg0NDAsImV4cCI6MjA2OTExNDQ0MH0.4zvuDZRmr6XGYy-quZMOzeXlc7mRBSAbk_o9Ml9CtAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});